### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by ykocoglu** [spartanhooah/homework3#1]
Hello,

Can you please provide the dataset "diabetes.mat" for hw3 if it's not a private dataset?

Thank you in advance.

**Comment by spartanhooah** [comment]
That was provided by the professor, I believe. I certainly don't have it any longer, sorry.

**Comment by ykocoglu** [comment]
Thank you for your response. You might want to somehow let other people know by writing a small info or attaching a text file because you might have more unnecessary emails in the future (one of them is mine). I was trying to practice ridge regression and was looking for resources. If you know any resources I would really appreciate it.

Sent from my iPhone

On Jan 30, 2019, at 12:29 PM, spartanhooah <notifications@github.com<mailto:notifications@github.com>> wrote:


That was provided by the professor, I believe. I certainly don't have it any longer, sorry.
